language: node_js
node_js:
  - "6"
  - "6.1.0"
  - "5.1"

cache:
  directories:
    - node_modules

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq silversearcher-ag

install:
  - npm install

script:
  - npm test
