os:
  - osx
language: node_js
node_js:
  - "6.1.0"

cache:
  directories:
    - node_modules

before_install:
  - brew update
  - brew install the_silver_searcher

install:
  - npm install

script:
  - npm test
